In [27]:
from os import environ
environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf
from icecream.icecream import ic

In [11]:
# Initialisation

x = tf.constant(4.0, shape=(1,1), dtype=tf.float32)
ic(x)
x = tf.constant([[1,2,3],[4,5,6]])
ic(x)
x = tf.ones((3, 3))
ic(x)
x = tf.eye(3)
ic(x)
x = tf.random.normal((3,3))
ic(x)
x = tf.range(3, 12, 2)
ic(x)
x = tf.cast(x, tf.float32)
ic(x)

None


ic| x: <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>
ic| x: <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
       array([[1, 2, 3],
              [4, 5, 6]], dtype=int32)>
ic| x: <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
       array([[1., 1., 1.],
              [1., 1., 1.],
              [1., 1., 1.]], dtype=float32)>
ic| x: <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
       array([[1., 0., 0.],
              [0., 1., 0.],
              [0., 0., 1.]], dtype=float32)>
ic| x: <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
       array([[ 0.09425247, -1.2505125 , -0.17653139],
              [-0.9704321 , -0.05855087,  0.1959745 ],
              [-0.0589675 , -0.7278496 ,  1.3940358 ]], dtype=float32)>
ic| x: <tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 3,  5,  7,  9, 11], dtype=int32)>
ic| x: <tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 3.,  5.,  7.,  9., 11.], dtype=float32)>


In [22]:
# Maths

x = tf.range(1, 4)
y = tf.range(5, 8)

ic(x, y)

ic(
    tf.add(x, y),
    x + y,
    tf.multiply(x, y),
    x * y,
    tf.pow(x, y),
    x ** y
)

# dotprod
ic(
    tf.tensordot(x, y, axes=1),
    tf.reduce_sum(x*y, axis=0)
)

# matmul
x = tf.constant([[0,0,2], [0,1,0], [1,0,3]])
y = tf.reshape(tf.range(1, 10), shape=(3,3))
ic(x, y)
ic(tf.matmul(x, y))

None

ic| x: <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
    y: <tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 6, 7], dtype=int32)>
ic| tf.add(x, y): <tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 6,  8, 10], dtype=int32)>
    x + y: <tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 6,  8, 10], dtype=int32)>
    tf.multiply(x, y): <tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 5, 12, 21], dtype=int32)>
    x * y: <tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 5, 12, 21], dtype=int32)>
    tf.pow(x, y): <tf.Tensor: shape=(3,), dtype=int32, numpy=array([   1,   64, 2187], dtype=int32)>
    x ** y: <tf.Tensor: shape=(3,), dtype=int32, numpy=array([   1,   64, 2187], dtype=int32)>
ic| tf.tensordot(x, y, axes=1): <tf.Tensor: shape=(), dtype=int32, numpy=38>
    tf.reduce_sum(x*y, axis=0): <tf.Tensor: shape=(), dtype=int32, numpy=38>
ic| tf.matmul(x, y): <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
                     array([[14, 16, 18],
        

In [28]:
# Indexes

x = tf.range(0, 12)

ic(
    x[:],
    x[1:],
    x[1:3],
    x[::2]
)

indeces = tf.constant([0, 3])
ic(tf.gather(x, indeces))

ic| x[:]: <tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>
    x[1:]: <tf.Tensor: shape=(11,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>
    x[1:3]: <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>
    x[::2]: <tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 0,  2,  4,  6,  8, 10], dtype=int32)>
ic| tf.gather(x, indeces): <tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 3], dtype=int32)>


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 3], dtype=int32)>

[3Blue1Brown](https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi)
[NN Stuff](https://www.youtube.com/playlist?list=PLkDaE6sCZn6Ec-XTbcX1uRg2_u4xOEky0)
[NN Stuff 2](https://www.youtube.com/playlist?list=PLkDaE6sCZn6Hn0vK8co82zjQtt3T2Nkqc)

In [32]:
# Basic Neural Network

from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.losses import SparseCategoricalCrossentropy
from keras.optimizers import Adam
from keras import Input, Model

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(-1, 28 ** 2).astype("float32") / 255.0
x_test = x_test.reshape(-1, 28 ** 2).astype("float32") / 255.0

# Sequential API

model = Sequential(
    [
        Input(shape=(28**2)),
        Dense(512, activation="relu"),
        Dense(256, activation="relu"),
        Dense(10)
    ]
)

model.compile(
    loss=SparseCategoricalCrossentropy(from_logits=True),
    optimizer=Adam(lr=0.001),
    metrics="accuracy"
)

model.fit(x_train, y_train, batch_size=32, epochs=5, verbose="2")
model.evaluate(x_test, y_test, batch_size=32, verbose="2")

Epoch 1/5
Epoch 2/5
Epoch 3/5
Epoch 4/5
Epoch 5/5


[0.08710572123527527, 0.9763000011444092]

In [37]:
# Functional API

inputs = Input(shape=784)
x = Dense(512, activation="relu", name="first_layer")(inputs)
x = Dense(256, activation="relu", name="second_layse")(x)
outputs = Dense(10, activation="softmax")(x)gp
model = Model(inputs=inputs, outputs=outputs)

model.compile(
    loss=SparseCategoricalCrossentropy(from_logits=False),
    optimizer=Adam(lr=0.001),
    metrics=["accuracy"]
)

model.fit(x_train, y_train, batch_size=32, epochs=5, verbose="2")
model.evaluate(x_test, y_test, batch_size=32, verbose="2")

Epoch 1/5
Epoch 2/5
Epoch 3/5
Epoch 4/5
Epoch 5/5


[0.0826604887843132, 0.977400004863739]

In [39]:
# CNNs

from keras.datasets import cifar10

physical_devices = tf.config.list_logical_devices("GPU")
ic(physical_devices)

ic| physical_devices: [LogicalDevice(name='/device:GPU:0', device_type='GPU')]


[LogicalDevice(name='/device:GPU:0', device_type='GPU')]